#!/bin/bash

if [ "$#" -ne 1 ]
then
    echo "USAGE: ./test FILENAME"
    exit 1
fi

echo "Using data file: $1"

python3 receiver.py 8000 FileReceived.txt & P1=$!
python3 sender.py localhost 8000 $1 256 16 600 0.1 seed1 & P2=$!

echo "Receiver Process: $P1"
echo "Sender Process: $P2"

checkpids() {
    echo ""
    if [[ $(pgrep --ns $P1 | grep $P1) == "" ]]
    then 
        echo "Sucessfully closed process $P1"
    else
        kill $P1
        echo "Killed Process $P1"
    fi

    if [[ $(pgrep --ns $P2 | grep $P2) == "" ]]
    then 
        echo "Sucessfully closed process $P2"
    else
        kill $P2
        echo "Killed Process $P2"
    fi
}

trap "checkpids" SIGINT

wait $P1 $P2

RED="\e[31m"
GREEN="\e[32m"
END="\e[0m"

if [[ $(diff FileReceived.txt $1) == "" ]]
then
    echo -e "${GREEN}\nPassed!\n${END}"
else
    echo -e "${RED}\nFailed!\n${END}"
    echo -e "Output: \n"
    diff FileReceived.txt $1
    echo ""
fi

echo -e "Sender_log.txt: \n"

cat Sender_log.txt

echo""

cat Receiver_log.txt

echo ""

